import streamlit as st
from PIL import Image
st.set_page_config("Regulamento", layout="wide")
lider=st.sidebar.button("Lider")
equipe=st.sidebar.button("Equipe")
reunioes=st.sidebar.button("Reunioes")
objetivos=st.sidebar.button("Objetivos")
if lider:
   st.header(":green[Simone Cavalcanti / Daniel Lobo]", divider="orange")
   col = st.columns((1,1,1))
   col[0].image("simone.PNG")
   col[1].image("daniel.PNG")
if equipe:
   st.header(":green[Equipe Regulamento]", divider="orange")
   col = st.columns((1,1,1,1))
   col[0].write(":green[Comercial/Cadastro/RH]")
   col[1].write(":blue[Capítulo - Abastecimento de Água]")
   col[2].write(":red[Capítulo - Esgotamento Sanitário]")
   col[3].write(":orange[Capítulo - Resíduos Sólidos]") 
   col[0].write("Júnior")
   col[0].write("Cyra Regina")
   col[0].write("Iolanda Telles")
   col[0].write("Gláucia Valadão")
   col[0].write("Jane Sizenandes")
   col[0].write("Alisson")
   col[0].write("Maria da Conceição Gois")
   col[1].write("João Manoel de Deus")
   col[1].write("Herotsan")
   col[1].write("Dalton Monteiro")
   col[1].write("Érika Carvalho")
   col[2].write("Samara")
   col[2].write("Juliana")
   col[2].write("Fabíola Bertinetti")
   col[3].write("Hermes Ávila")
   col[3].write("Ivone")
if reunioes:
   st.markdown("Aqui teremos as reunioes realizadas")
if objetivos:
   st.markdown("Este espaço pode ser ocupado com diversas coisas")
